#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Restituye la acentuacion del texto en espanol de la interfaz y de los datos.

Solo toca literales de cadena que son texto visible. Se saltan las rutas, los
identificadores del modelo de datos, los nombres de clase y los valores que
funcionan como clave, porque cambiarlos romperia referencias.
"""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

WORDS = {
    # nomenclatura y anatomia
    'esteroidogenesis': 'esteroidogénesis', 'Esteroidogenesis': 'Esteroidogénesis',
    'via': 'vía', 'Via': 'Vía', 'vias': 'vías', 'Vias': 'Vías',
    'organo': 'órgano', 'Organo': 'Órgano', 'organos': 'órganos', 'Organos': 'Órganos',
    'organulo': 'orgánulo', 'Organulo': 'Orgánulo', 'organulos': 'orgánulos',
    'molecula': 'molécula', 'Molecula': 'Molécula', 'moleculas': 'moléculas', 'Moleculas': 'Moléculas',
    'molecular': 'molecular', 'celula': 'célula', 'Celula': 'Célula', 'celulas': 'células',
    'nucleo': 'núcleo', 'Nucleo': 'Núcleo', 'nucleos': 'núcleos',
    'atomo': 'átomo', 'Atomo': 'Átomo', 'atomos': 'átomos', 'Atomos': 'Átomos',
    'atomica': 'atómica', 'atomico': 'atómico',
    'reticulo': 'retículo', 'Reticulo': 'Retículo',
    'endoplasmico': 'endoplásmico', 'Endoplasmico': 'Endoplásmico',
    'mitocondrial': 'mitocondrial', 'glandula': 'glándula', 'Glandula': 'Glándula',
    'higado': 'hígado', 'Higado': 'Hígado', 'rinon': 'riñón', 'Rinon': 'Riñón',
    'corazon': 'corazón', 'Corazon': 'Corazón', 'prostata': 'próstata', 'Prostata': 'Próstata',
    'utero': 'útero', 'Utero': 'Útero', 'testiculo': 'testículo', 'Testiculo': 'Testículo',
    'testiculos': 'testículos', 'ovarico': 'ovárico', 'Ovarico': 'Ovárico',
    'ovarios': 'ovarios', 'foliculo': 'folículo', 'Foliculo': 'Folículo',
    'foliculos': 'folículos', 'folicular': 'folicular', 'sebacea': 'sebácea',
    'luteo': 'lúteo', 'Luteo': 'Lúteo', 'lutea': 'lútea', 'Lutea': 'Lútea',
    'musculo': 'músculo', 'Musculo': 'Músculo', 'esqueletico': 'esquelético',
    'laringe': 'laringe', 'craneo': 'cráneo', 'epididimo': 'epidídimo',
    'hipofisis': 'hipófisis', 'Hipofisis': 'Hipófisis', 'hipofisaria': 'hipofisaria',
    'hipotalamo': 'hipotálamo', 'Hipotalamo': 'Hipotálamo',
    'suprarrenal': 'suprarrenal', 'gonada': 'gónada', 'gonadal': 'gonadal',
    'hipogonadismo': 'hipogonadismo', 'cartilago': 'cartílago', 'Cartilago': 'Cartílago',
    'oseo': 'óseo', 'osea': 'ósea', 'sanguineo': 'sanguíneo',

    # quimica y proceso
    'sintesis': 'síntesis', 'Sintesis': 'Síntesis',
    'sintetiza': 'sintetiza', 'sintetico': 'sintético', 'Sintetico': 'Sintético',
    'sinteticos': 'sintéticos', 'sintetica': 'sintética',
    'escision': 'escisión', 'Escision': 'Escisión',
    'oxidacion': 'oxidación', 'Oxidacion': 'Oxidación',
    'reduccion': 'reducción', 'Reduccion': 'Reducción',
    'hidroxilacion': 'hidroxilación', 'Hidroxilacion': 'Hidroxilación',
    'aromatizacion': 'aromatización', 'Aromatizacion': 'Aromatización',
    'sulfatacion': 'sulfatación', 'Sulfatacion': 'Sulfatación',
    'desulfatacion': 'desulfatación', 'isomerizacion': 'isomerización',
    'conversion': 'conversión', 'Conversion': 'Conversión',
    'conjugacion': 'conjugación', 'transformacion': 'transformación',
    'Transformacion': 'Transformación', 'formacion': 'formación',
    'inactivacion': 'inactivación', 'Inactivacion': 'Inactivación',
    'activacion': 'activación', 'inhibicion': 'inhibición', 'Inhibicion': 'Inhibición',
    'induccion': 'inducción', 'Induccion': 'Inducción',
    'produccion': 'producción', 'Produccion': 'Producción',
    'secrecion': 'secreción', 'Secrecion': 'Secreción',
    'excrecion': 'excreción', 'reabsorcion': 'reabsorción',
    'absorcion': 'absorción', 'disociacion': 'disociación',
    'proliferacion': 'proliferación', 'Proliferacion': 'Proliferación',
    'maduracion': 'maduración', 'ovulacion': 'ovulación', 'Ovulacion': 'Ovulación',
    'menstruacion': 'menstruación', 'gestacion': 'gestación', 'Gestacion': 'Gestación',
    'lactancia': 'lactancia', 'virilizacion': 'virilización', 'Virilizacion': 'Virilización',
    'feminizacion': 'feminización', 'diferenciacion': 'diferenciación',
    'expresion': 'expresión', 'Expresion': 'Expresión',
    'concentracion': 'concentración', 'Concentracion': 'Concentración',
    'concentraciones': 'concentraciones', 'distribucion': 'distribución',
    'retroalimentacion': 'retroalimentación', 'Retroalimentacion': 'Retroalimentación',
    'regulacion': 'regulación', 'Regulacion': 'Regulación',
    'estimulo': 'estímulo', 'Estimulo': 'Estímulo', 'estimula': 'estimula',
    'limitante': 'limitante', 'union': 'unión', 'Union': 'Unión',
    'afinidad': 'afinidad', 'catabolismo': 'catabolismo',
    'aromatasa': 'aromatasa', 'reductasa': 'reductasa', 'liasa': 'liasa',

    # interfaz
    'accion': 'acción', 'Accion': 'Acción', 'acciones': 'acciones',
    'interaccion': 'interacción', 'Interaccion': 'Interacción',
    'interacciones': 'interacciones', 'Interacciones': 'Interacciones',
    'seleccion': 'selección', 'Seleccion': 'Selección',
    'representacion': 'representación', 'Representacion': 'Representación',
    'representaciones': 'representaciones',
    'superposicion': 'superposición', 'Superposicion': 'Superposición',
    'posicion': 'posición', 'Posicion': 'Posición', 'posiciones': 'posiciones',
    'proporcion': 'proporción', 'proyeccion': 'proyección',
    'navegacion': 'navegación', 'Navegacion': 'Navegación',
    'aplicacion': 'aplicación', 'compilacion': 'compilación',
    'verificacion': 'verificación', 'Verificacion': 'Verificación',
    'comprobacion': 'comprobación', 'Comprobacion': 'Comprobación',
    'comprobaciones': 'comprobaciones',
    'informacion': 'información', 'Informacion': 'Información',
    'descripcion': 'descripción', 'Descripcion': 'Descripción',
    'explicacion': 'explicación', 'Explicacion': 'Explicación',
    'simulacion': 'simulación', 'Simulacion': 'Simulación',
    'animacion': 'animación', 'Animacion': 'Animación',
    'numeracion': 'numeración', 'Numeracion': 'Numeración',
    'anotacion': 'anotación', 'Anotacion': 'Anotación',
    'correspondencia': 'correspondencia', 'conformacion': 'conformación',
    'Conformacion': 'Conformación', 'conformaciones': 'conformaciones',
    'procedencia': 'procedencia', 'referencia': 'referencia',
    'Referencia': 'Referencia', 'referencias': 'referencias',
    'autoevaluacion': 'autoevaluación', 'Autoevaluacion': 'Autoevaluación',
    'elegibilidad': 'elegibilidad', 'Elegibilidad': 'Elegibilidad',
    'anticoncepcion': 'anticoncepción', 'Anticoncepcion': 'Anticoncepción',
    'administracion': 'administración', 'combinacion': 'combinación',
    'categoria': 'categoría', 'Categoria': 'Categoría', 'categorias': 'categorías',
    'Categorias': 'Categorías',
    'analitico': 'analítico', 'analitica': 'analítica', 'Analitico': 'Analítico',
    'diagnostico': 'diagnóstico', 'Diagnostico': 'Diagnóstico',
    'diagnostica': 'diagnóstica', 'clinico': 'clínico', 'Clinico': 'Clínico',
    'clinica': 'clínica', 'Clinica': 'Clínica', 'clinicos': 'clínicos',
    'clinicas': 'clínicas', 'Clinicas': 'Clínicas',
    'farmaco': 'fármaco', 'Farmaco': 'Fármaco', 'farmacos': 'fármacos',
    'Farmacos': 'Fármacos', 'farmacologico': 'farmacológico',
    'Farmacologico': 'Farmacológico', 'farmacologica': 'farmacológica',
    'farmacologicos': 'farmacológicos', 'farmacologicas': 'farmacológicas',
    'Farmacologicas': 'Farmacológicas', 'farmacocinetica': 'farmacocinética',
    'Farmacocinetica': 'Farmacocinética',
    'metabolico': 'metabólico', 'metabolica': 'metabólica',
    'enzimatico': 'enzimático', 'Enzimatico': 'Enzimático',
    'enzimatica': 'enzimática', 'Enzimatica': 'Enzimática',
    'enzimaticos': 'enzimáticos', 'enzimaticas': 'enzimáticas',
    'deficit': 'déficit', 'Deficit': 'Déficit', 'deficits': 'déficits',
    'Deficits': 'Déficits', 'deficiencia': 'deficiencia',
    'geneticos': 'genéticos', 'genetica': 'genética',
    'cromosomico': 'cromosómico', 'fisiologia': 'fisiología',
    'Fisiologia': 'Fisiología', 'fisiologico': 'fisiológico',
    'fisiologica': 'fisiológica', 'patologia': 'patología',
    'bioquimica': 'bioquímica', 'Bioquimica': 'Bioquímica',
    'bioquimico': 'bioquímico', 'quimica': 'química', 'Quimica': 'Química',
    'anatomica': 'anatómica', 'Anatomica': 'Anatómica', 'anatomia': 'anatomía',
    'Anatomia': 'Anatomía', 'esquematico': 'esquemático', 'Esquematico': 'Esquemático',
    'esquematica': 'esquemática', 'Esquematica': 'Esquemática',
    'esquematicas': 'esquemáticas', 'cualitativo': 'cualitativo',
    'grafico': 'gráfico', 'grafica': 'gráfica', 'topologico': 'topológico',
    'geometrico': 'geométrico', 'geometria': 'geometría', 'Geometria': 'Geometría',
    'tridimensional': 'tridimensional', 'parametrico': 'paramétrico',
    'cristalografica': 'cristalográfica', 'bibliografica': 'bibliográfica',
    'bibliograficas': 'bibliográficas',
    'automaticamente': 'automáticamente', 'automatico': 'automático',
    'practica': 'práctica', 'Practica': 'Práctica', 'practico': 'práctico',
    'Practico': 'Práctico', 'unico': 'único', 'Unico': 'Único',
    'unica': 'única', 'Unica': 'Única', 'unicos': 'únicos', 'unicas': 'únicas',
    'ultimo': 'último', 'ultima': 'última', 'proximo': 'próximo',
    'proximas': 'próximas', 'basico': 'básico', 'basica': 'básica',
    'tipico': 'típico', 'tipica': 'típica', 'especifico': 'específico',
    'especifica': 'específica', 'selectivo': 'selectivo', 'selectiva': 'selectiva',
    'multiples': 'múltiples', 'Multiples': 'Múltiples',
    'menstrual': 'menstrual', 'climaterio': 'climaterio',
    'seleccionar': 'seleccionar', 'Seleccionar': 'Seleccionar',
    'ademas': 'además', 'Ademas': 'Además', 'aqui': 'aquí', 'Aqui': 'Aquí',
    'asi': 'así', 'Asi': 'Así', 'mas': 'más', 'Mas': 'Más',
    'segun': 'según', 'Segun': 'Según', 'tambien': 'también', 'Tambien': 'También',
    'esta': 'esta', 'estan': 'están', 'Estan': 'Están',
    'esten': 'estén', 'sera': 'será', 'seran': 'serán',
    'aun': 'aún', 'solo': 'solo', 'despues': 'después', 'Despues': 'Después',
    'tras': 'tras', 'porque': 'porque', 'que': 'que', 'quien': 'quien',
    'cuantos': 'cuántos', 'cuando': 'cuando',
    'algun': 'algún', 'ningun': 'ningún', 'Ningun': 'Ningún',
    'estandar': 'estándar', 'Estandar': 'Estándar',
    'facil': 'fácil', 'dificil': 'difícil', 'dificultad': 'dificultad',
    'util': 'útil', 'Util': 'Útil', 'utiles': 'útiles', 'Utiles': 'Útiles',
    'tipografia': 'tipografía', 'Tipografia': 'Tipografía',
    'numero': 'número', 'Numero': 'Número', 'numeros': 'números',
    'metodo': 'método', 'Metodo': 'Método', 'metodos': 'métodos',
    'Metodos': 'Métodos', 'periodo': 'período',
    'linea': 'línea', 'Linea': 'Línea', 'lineas': 'líneas',
    'pagina': 'página', 'maximo': 'máximo', 'Maximo': 'Máximo',
    'minimo': 'mínimo', 'Minimo': 'Mínimo', 'minima': 'mínima',
    'maxima': 'máxima', 'Maxima': 'Máxima',
    'rapido': 'rápido', 'rapida': 'rápida', 'rapidos': 'rápidos', 'rapidez': 'rapidez',
    'energia': 'energía', 'dia': 'día', 'Dia': 'Día', 'dias': 'días', 'Dias': 'Días',
    'ano': 'año', 'anos': 'años', 'Anos': 'Años',
    'proteina': 'proteína', 'Proteina': 'Proteína', 'proteinas': 'proteínas',
    'protege': 'protege', 'perdida': 'pérdida', 'Perdida': 'Pérdida',
    'salina': 'salina', 'ambiguos': 'ambiguos', 'genitales': 'genitales',
    'hormonal': 'hormonal', 'hormona': 'hormona', 'Hormona': 'Hormona',
    'hormonas': 'hormonas', 'Hormonas': 'Hormonas',
    'androgeno': 'andrógeno', 'Androgeno': 'Andrógeno',
    'androgenos': 'andrógenos', 'Androgenos': 'Andrógenos',
    'androgenica': 'androgénica', 'androgenico': 'androgénico',
    'androgenodependientes': 'androgenodependientes',
    'estrogeno': 'estrógeno', 'Estrogeno': 'Estrógeno',
    'estrogenos': 'estrógenos', 'Estrogenos': 'Estrógenos',
    'estrogenica': 'estrogénica', 'estrogenico': 'estrogénico',
    'gestageno': 'gestágeno', 'Gestageno': 'Gestágeno',
    'gestagenos': 'gestágenos', 'Gestagenos': 'Gestágenos',
    'progestageno': 'progestágeno', 'Progestageno': 'Progestágeno',
    'progestagenos': 'progestágenos', 'Progestagenos': 'Progestágenos',
    'progestagenica': 'progestagénica',
    'glucocorticoide': 'glucocorticoide', 'mineralocorticoide': 'mineralocorticoide',
    'corticoide': 'corticoide', 'corticoides': 'corticoides',
    'esteroide': 'esteroide', 'esteroides': 'esteroides',
    'esteroidea': 'esteroidea', 'esteroideas': 'esteroideas',
    'esteroideo': 'esteroideo', 'esteroideos': 'esteroideos',
    'esteroidogenica': 'esteroidogénica', 'esteroidogenicas': 'esteroidogénicas',
    'esteroidogenicos': 'esteroidogénicos',
    'antiandrogeno': 'antiandrógeno', 'Antiandrogeno': 'Antiandrógeno',
    'antiandrogenos': 'antiandrógenos', 'Antiandrogenos': 'Antiandrógenos',
    'antiandrogenica': 'antiandrogénica', 'antimineralocorticoide': 'antimineralocorticoide',
    'anabolizante': 'anabolizante', 'anabolizantes': 'anabolizantes',
    'Anabolizantes': 'Anabolizantes',
    'inhibidor': 'inhibidor', 'Inhibidores': 'Inhibidores',
    'metabolito': 'metabolito', 'metabolitos': 'metabolitos',
    'Metabolito': 'Metabolito', 'Metabolitos': 'Metabolitos',
    'precursor': 'precursor', 'Precursor': 'Precursor',
    'precursores': 'precursores', 'Precursores': 'Precursores',
    'intermediario': 'intermediario', 'endogena': 'endógena', 'Endogena': 'Endógena',
    'endogeno': 'endógeno', 'endogenas': 'endógenas', 'endogenos': 'endógenos',
    'exogena': 'exógena', 'exogeno': 'exógeno',
    'perifericos': 'periféricos', 'perifericas': 'periféricas',
    'periferica': 'periférica', 'periferico': 'periférico',
    'circadiano': 'circadiano', 'hepatico': 'hepático', 'hepatica': 'hepática',
    'renal': 'renal', 'cutanea': 'cutánea', 'sistemica': 'sistémica',
    'nefropatia': 'nefropatía', 'retinopatia': 'retinopatía',
    'neuropatia': 'neuropatía', 'hepatopatia': 'hepatopatía',
    'trombofilia': 'trombofilia', 'tromboembolismo': 'tromboembolismo',
    'tromboembolico': 'tromboembólico', 'trombotico': 'trombótico',
    'hipertension': 'hipertensión', 'Hipertension': 'Hipertensión',
    'hipopotasemia': 'hipopotasemia', 'hiperpotasemia': 'hiperpotasemia',
    'hiponatremia': 'hiponatremia', 'hipovolemia': 'hipovolemia',
    'migrana': 'migraña', 'Migrana': 'Migraña', 'cefalea': 'cefalea',
    'nauseas': 'náuseas', 'artralgias': 'artralgias',
    'ginecomastia': 'ginecomastia', 'hirsutismo': 'hirsutismo',
    'alopecia': 'alopecia', 'acne': 'acné', 'Acne': 'Acné',
    'atrofia': 'atrofia', 'anemia': 'anemia', 'ferropenica': 'ferropénica',
    'infertilidad': 'infertilidad', 'espermatogenesis': 'espermatogénesis',
    'azoospermia': 'azoospermia', 'libido': 'libido',
    'pubertad': 'pubertad', 'adrenarquia': 'adrenarquia', 'telarquia': 'telarquia',
    'pubarquia': 'pubarquia', 'menopausia': 'menopausia',
    'posmenopausia': 'posmenopausia', 'posmenopausico': 'posmenopáusico',
    'premenopausia': 'premenopausia', 'posparto': 'posparto',
    'neonatal': 'neonatal', 'fetal': 'fetal', 'feto': 'feto',
    'placenta': 'placenta', 'placentaria': 'placentaria',
    'fetoplacentaria': 'fetoplacentaria', 'endometrio': 'endometrio',
    'endometrial': 'endometrial', 'miometrio': 'miometrio',
    'granulosa': 'granulosa', 'teca': 'teca', 'leydig': 'leydig',
    'oncologico': 'oncológico', 'oncologica': 'oncológica',
    'castracion': 'castración', 'meningioma': 'meningioma',
    'hepatotoxicidad': 'hepatotoxicidad', 'policitemia': 'policitemia',
    'cribado': 'cribado', 'gonadectomia': 'gonadectomía',
    'sustitutivo': 'sustitutivo', 'sustitucion': 'sustitución',
    'Sustitucion': 'Sustitución', 'tratamiento': 'tratamiento',
    'Tratamiento': 'Tratamiento', 'indicaciones': 'indicaciones',
    'Indicaciones': 'Indicaciones', 'contraindicaciones': 'contraindicaciones',
    'Contraindicaciones': 'Contraindicaciones', 'adversos': 'adversos',
    'insuficiencia': 'insuficiencia', 'hiperplasia': 'hiperplasia',
    'carcinoma': 'carcinoma', 'herencia': 'herencia', 'Herencia': 'Herencia',
    'recesiva': 'recesiva', 'autosomica': 'autosómica', 'Autosomica': 'Autosómica',
    'fenotipo': 'fenotipo', 'Fenotipo': 'Fenotipo', 'cariotipo': 'cariotipo',
    'identidad': 'identidad', 'Identidad': 'Identidad',
    'territorio': 'territorio', 'Territorio': 'Territorio',
    'territorios': 'territorios', 'Territorios': 'Territorios',
    'compartimento': 'compartimento', 'Compartimento': 'Compartimento',
    'cofactor': 'cofactor', 'cofactores': 'cofactores', 'Cofactores': 'Cofactores',
    'donante': 'donante', 'Donante': 'Donante', 'electrones': 'electrones',
    'actividad': 'actividad', 'Actividad': 'Actividad', 'actividades': 'actividades',
    'Actividades': 'Actividades', 'residual': 'residual',
    'reaccion': 'reacción', 'Reaccion': 'Reacción', 'reacciones': 'reacciones',
    'Reacciones': 'Reacciones', 'enzima': 'enzima', 'Enzima': 'Enzima',
    'enzimas': 'enzimas', 'Enzimas': 'Enzimas', 'sustrato': 'sustrato',
    'producto': 'producto', 'Producto': 'Producto', 'productos': 'productos',
    'receptor': 'receptor', 'Receptor': 'Receptor', 'receptores': 'receptores',
    'Receptores': 'Receptores', 'ligando': 'ligando', 'Ligando': 'Ligando',
    'ligandos': 'ligandos', 'Ligandos': 'Ligandos',
    'antagonista': 'antagonista', 'agonista': 'agonista', 'modulador': 'modulador',
    'tejido': 'tejido', 'Tejido': 'Tejido', 'tejidos': 'tejidos', 'Tejidos': 'Tejidos',
    'laboratorio': 'laboratorio', 'Laboratorio': 'Laboratorio',
    'analito': 'analito', 'Analito': 'Analito', 'analitos': 'analitos',
    'rango': 'rango', 'Rangos': 'Rangos', 'rangos': 'rangos',
    'orientativos': 'orientativos', 'orientativo': 'orientativo',
    'interpretacion': 'interpretación', 'Interpretacion': 'Interpretación',
    'marcador': 'marcador', 'lectura': 'lectura', 'Lecturas': 'Lecturas',
    'lecturas': 'lecturas', 'fuente': 'fuente', 'Fuente': 'Fuente',
    'fuentes': 'fuentes', 'Fuentes': 'Fuentes', 'pendiente': 'pendiente',
    'verificada': 'verificada', 'comprobada': 'comprobada',
    'guiado': 'guiado', 'recorrido': 'recorrido', 'Recorrido': 'Recorrido',
    'paso': 'paso', 'Paso': 'Paso', 'pasos': 'pasos', 'Pasos': 'Pasos',
    'mapa': 'mapa', 'Mapa': 'Mapa', 'atlas': 'atlas', 'Atlas': 'Atlas',
    'comparador': 'comparador', 'Comparador': 'Comparador',
    'simulador': 'simulador', 'Simulador': 'Simulador',
    'ciclo': 'ciclo', 'Ciclo': 'Ciclo', 'escala': 'escala', 'Escala': 'Escala',
    'escalas': 'escalas', 'Escalas': 'Escalas',
    'anillo': 'anillo', 'Anillo': 'Anillo', 'anillos': 'anillos', 'Anillos': 'Anillos',
    'cadena': 'cadena', 'Cadena': 'Cadena', 'lateral': 'lateral',
    'aromatico': 'aromático', 'Aromatico': 'Aromático', 'aromatica': 'aromática',
    'hidroxilo': 'hidroxilo', 'ceto': 'ceto', 'cetona': 'cetona',
    'funcionales': 'funcionales', 'grupo': 'grupo', 'Grupos': 'Grupos',
    'sustituyente': 'sustituyente', 'Sustituyente': 'Sustituyente',
    'sustituyentes': 'sustituyentes', 'Sustituyentes': 'Sustituyentes',
    'desviacion': 'desviación', 'Desviacion': 'Desviación',
    'cuadratica': 'cuadrática', 'media': 'media', 'angstrom': 'ángstrom',
    'formula': 'fórmula', 'Formula': 'Fórmula', 'formulas': 'fórmulas',
    'masa': 'masa', 'Masa': 'Masa', 'molar': 'molar',
    'familia': 'familia', 'Familia': 'Familia', 'familias': 'familias',
    'papel': 'papel', 'Papel': 'Papel', 'pesados': 'pesados',
    'hidrogenos': 'hidrógenos', 'Hidrogenos': 'Hidrógenos', 'hidrogeno': 'hidrógeno',
    'superficie': 'superficie', 'Superficie': 'Superficie',
    'esferas': 'esferas', 'Esferas': 'Esferas', 'varillas': 'varillas',
    'Varillas': 'Varillas', 'bolas': 'bolas', 'Bolas': 'Bolas',
    'elemento': 'elemento', 'Elemento': 'Elemento', 'color': 'color', 'Color': 'Color',
    'tema': 'tema', 'Tema': 'Tema', 'buscar': 'buscar', 'Buscar': 'Buscar',
    'filtrar': 'filtrar', 'Filtrar': 'Filtrar', 'coincidencias': 'coincidencias',
    'siguiente': 'siguiente', 'Siguiente': 'Siguiente', 'anterior': 'anterior',
    'Anterior': 'Anterior', 'reiniciar': 'reiniciar', 'Reiniciar': 'Reiniciar',
    'terminar': 'terminar', 'Terminar': 'Terminar', 'explorar': 'explorar',
    'Explorar': 'Explorar', 'atras': 'atrás', 'Atras': 'Atrás',
    'cerrar': 'cerrar', 'Cerrar': 'Cerrar', 'ficha': 'ficha', 'Ficha': 'Ficha',
    'fichas': 'fichas', 'construccion': 'construcción', 'Construccion': 'Construcción',
    'preparacion': 'preparación', 'registrados': 'registrados',
    'registrada': 'registrada', 'registradas': 'registradas', 'registrado': 'registrado',
    'todavia': 'todavía', 'pregunta': 'pregunta', 'Pregunta': 'Pregunta',
    'preguntas': 'preguntas', 'Preguntas': 'Preguntas',
    'correcto': 'correcto', 'Correcto': 'Correcto', 'respuesta': 'respuesta',
    'aciertos': 'aciertos', 'respondidas': 'respondidas', 'responder': 'responder',
    'menos': 'menos', 'Menos': 'Menos', 'inaceptable': 'inaceptable',
    'ventajas': 'ventajas', 'riesgos': 'riesgos', 'riesgo': 'riesgo',
    'restriccion': 'restricción', 'Restriccion': 'Restricción',
    'condicion': 'condición', 'Condicion': 'Condición', 'condiciones': 'condiciones',
    'Condiciones': 'Condiciones', 'nota': 'nota', 'Nota': 'Nota', 'notas': 'notas',
    'aviso': 'aviso', 'Aviso': 'Aviso', 'alcance': 'alcance', 'Alcance': 'Alcance',
    'docente': 'docente', 'edicion': 'edición', 'Edicion': 'Edición',
    'vigente': 'vigente', 'nacional': 'nacional', 'correspondiente': 'correspondiente',
    'consultar': 'consultar', 'decision': 'decisión', 'Decision': 'Decisión',
    'inyectable': 'inyectable', 'implante': 'implante', 'subdermico': 'subdérmico',
    'Subdermico': 'Subdérmico', 'pildora': 'píldora', 'Pildora': 'Píldora',
    'parche': 'parche', 'anillo': 'anillo', 'cobre': 'cobre',
    'combinado': 'combinado', 'Combinado': 'Combinado',
    'puerperal': 'puerperal', 'trofoblastica': 'trofoblástica',
    'maligna': 'maligna', 'miomas': 'miomas', 'cavidad': 'cavidad',
    'uterino': 'uterino', 'estudiarlo': 'estudiarlo', 'estudiado': 'estudiado',
    'continuar': 'continuar', 'Continuar': 'Continuar',
    'tabaquismo': 'tabaquismo', 'Tabaquismo': 'Tabaquismo',
    'cigarrillos': 'cigarrillos', 'obesidad': 'obesidad', 'Obesidad': 'Obesidad',
    'indice': 'índice', 'Indice': 'Índice', 'corporal': 'corporal',
    'endometriosis': 'endometriosis', 'antecedente': 'antecedente',
    'Antecedente': 'Antecedente', 'venoso': 'venoso', 'conocida': 'conocida',
    'controlada': 'controlada', 'cirrosis': 'cirrosis', 'descompensada': 'descompensada',
    'lupus': 'lupus', 'anticuerpos': 'anticuerpos', 'antifosfolipido': 'antifosfolípido',
    'positivos': 'positivos', 'diabetes': 'diabetes', 'cancer': 'cáncer',
    'Cancer': 'Cáncer', 'actual': 'actual', 'pasado': 'pasado', 'recidiva': 'recidiva',
    'grave': 'grave', 'activa': 'activa', 'filiado': 'filiado', 'sepsis': 'sepsis',
    'gestacional': 'gestacional', 'levonorgestrel': 'levonorgestrel',
    'etonogestrel': 'etonogestrel', 'medroxiprogesterona': 'medroxiprogesterona',
    'potentes': 'potentes', 'inductores': 'inductores', 'enzimaticos': 'enzimáticos',
    # segunda revision de vocabulario
    'desvia': 'desvía',
    'manana': 'mañana',
    'determinacion': 'determinación',
    'Determinacion': 'Determinación',
    'fraccion': 'fracción',
    'Fraccion': 'Fracción',
    'extraccion': 'extracción',
    'Extraccion': 'Extracción',
    'funcion': 'función',
    'Funcion': 'Función',
    'funciona': 'funciona',
    'funcional': 'funcional',
    'exposicion': 'exposición',
    'Exposicion': 'Exposición',
    'antiandrogenico': 'antiandrogénico',
    'antiandrogenicos': 'antiandrogénicos',
    'Ester': 'Éster',
    'ester': 'éster',
    'esteres': 'ésteres',
    'Esteres': 'Ésteres',
    'inyeccion': 'inyección',
    'Inyeccion': 'Inyección',
    'inyecciones': 'inyecciones',
    'sintomas': 'síntomas',
    'Sintomas': 'Síntomas',
    'sintoma': 'síntoma',
    'climatericos': 'climatéricos',
    'climaterica': 'climatérica',
    'medicos': 'médicos',
    'Medicos': 'Médicos',
    'medica': 'médica',
    'medico': 'médico',
    'distorsion': 'distorsión',
    'Distorsion': 'Distorsión',
    'revision': 'revisión',
    'Revision': 'Revisión',
    'revisiones': 'revisiones',
    'localizacion': 'localización',
    'Localizacion': 'Localización',
    'congenita': 'congénita',
    'Congenita': 'Congénita',
    'congenito': 'congénito',
    'panoramica': 'panorámica',
    'Panoramica': 'Panorámica',
    'enfasis': 'énfasis',
    'clasica': 'clásica',
    'Clasica': 'Clásica',
    'clasico': 'clásico',
    'biologicas': 'biológicas',
    'biologica': 'biológica',
    'biologico': 'biológico',
    'repercusion': 'repercusión',
    'Repercusion': 'Repercusión',
    'farmacologia': 'farmacología',
    'Farmacologia': 'Farmacología',
    'vision': 'visión',
    'Vision': 'Visión',
    'decision': 'decisión',
    'presion': 'presión',
    'Presion': 'Presión',
    'region': 'región',
    'Region': 'Región',
    'analisis': 'análisis',
    'Analisis': 'Análisis',
    'hipercortisolismo': 'hipercortisolismo',
    'subcelular': 'subcelular',
    'citoplasma': 'citoplasma',
    'chaperonas': 'chaperonas',
    'oxigenados': 'oxigenados',
    'emparejados': 'emparejados',
    'senal': 'señal',
    'Senal': 'Señal',
    'senales': 'señales',
    'ninguna': 'ninguna',
    'Ninguna': 'Ninguna',
    'nucleofilo': 'nucleófilo',
    'suprarrenales': 'suprarrenales',
    'esteroidogenesis': 'esteroidogénesis',
    'metabolizados': 'metabolizados',
    'conjugacion': 'conjugación',
    'Conjugacion': 'Conjugación',
    'administracion': 'administración',
    'Administracion': 'Administración',
    'preparados': 'preparados',
    'determinaciones': 'determinaciones',
    'seleccionados': 'seleccionados',
    'individualizada': 'individualizada',
    'reversible': 'reversible',
    'irreversible': 'irreversible',
    'competitivo': 'competitivo',
    'alostérico': 'alostérico',
    'alosterico': 'alostérico',
    'alosterica': 'alostérica',
    'espiro': 'espiro',
    'lactona': 'lactona',
    'sulfato': 'sulfato',
}

STR_RE = re.compile(r"(?P<q>['\"])(?P<body>(?:\\.|(?!(?P=q))[^\\\n])*)(?P=q)")
SKIP = re.compile(r"^(#|[a-z]+:[A-Za-z0-9_]*$|[a-z0-9_.\-]+$|https?://|[A-Z_]+$|\d)")
WORD_RE = re.compile(r'[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+')


def fix_text(text):
    return WORD_RE.sub(lambda m: WORDS.get(m.group(0), m.group(0)), text)


def process(path):
    src = open(path, encoding='utf-8').read()
    changed = [0]

    def repl(m):
        body = m.group('body')
        if not body or SKIP.match(body):
            return m.group(0)
        new = fix_text(body)
        if new != body:
            changed[0] += 1
        return m.group('q') + new + m.group('q')

    out = STR_RE.sub(repl, src)
    if out != src:
        open(path, 'w', encoding='utf-8').write(out)
    return changed[0]


def main():
    total, files = 0, 0
    for base, dirs, names in os.walk(os.path.join(ROOT, 'src')):
        dirs[:] = [d for d in dirs if d != 'data']
        for n in names:
            if n.endswith('.js'):
                c = process(os.path.join(base, n))
                if c: files += 1; total += c
    for n in ['gen-pathway.py', 'gen-organs.py', 'gen-clinical.py', 'molecules-manifest.py']:
        c = process(os.path.join(ROOT, 'tools', n))
        if c: files += 1; total += c
    print('  %d cadenas acentuadas en %d archivos' % (total, files))


if __name__ == '__main__':
    main()
