# -*- coding: utf-8 -*-
"""Manifiesto molecular del atlas.

Cada entrada declara: identificador, nombres, familia, papel, SMILES isomerico,
formula esperada (control duro: si RDKit calcula otra, el build falla) y el CID
de PubChem con el que verificar la entrada cuando haya acceso a la red.

'ik' es la clave InChI de referencia. Cuando esta presente, el generador exige
que coincida con la que calcula RDKit a partir del SMILES: es la comprobacion
mas fuerte disponible sin red, porque cubre conectividad y estereoquimica.
Cuando falta, la molecula queda marcada como pendiente de verificacion y la
ficha lo dice.
"""

M = [
    # ---------------------------------------------------------- precursores ---
    dict(id='mol:colesterol', es='Colesterol', en='Cholesterol', corto='Colesterol',
         family='precursor', role=['endogena'], cid=5997, formula='C27H46O',
         ik='HVYWMOMLDIMFJA-DPAQBDIFSA-N',
         smiles='CC(C)CCC[C@@H](C)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='mol:pregnenolona', es='Pregnenolona', en='Pregnenolone', corto='Preg',
         family='precursor', role=['endogena', 'intermediario'], cid=8955, formula='C21H32O2',
         ik='ORNBQBCIOKFOEO-QGVNFLHTSA-N',
         smiles='CC(=O)[C@H]1CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='mol:17oh_pregnenolona', es='17α-hidroxipregnenolona', en='17α-Hydroxypregnenolone',
         corto='17-OH-Preg', family='precursor', role=['endogena', 'intermediario'], cid=91451,
         formula='C21H32O3', ik='JERGUCIJOXJXHF-GCOKGBOCSA-N',
         smiles='CC(=O)[C@]1(O)CC[C@H]2[C@@H]3CC=C4C[C@@H](O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='mol:dhea', es='Dehidroepiandrosterona', en='Dehydroepiandrosterone', corto='DHEA',
         family='androgeno', role=['endogena', 'intermediario'], cid=5881, formula='C19H28O2',
         ik='FMGSKLZLMKYGDP-USOAJAOKSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@]34C)[C@@H]1CCC2=O'),
    dict(id='mol:dhea_s', es='Sulfato de DHEA', en='DHEA sulfate', corto='DHEA-S',
         family='androgeno', role=['endogena'], cid=12594, formula='C19H28O5S',
         ik='CZWCKYRVOZZJNM-USOAJAOKSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](OS(=O)(=O)O)CC[C@]34C)[C@@H]1CCC2=O'),
    dict(id='mol:androstenediol', es='Androstenediol', en='Androstenediol', corto='A5-diol',
         family='androgeno', role=['endogena', 'intermediario'], cid=10634, formula='C19H30O2',
         ik='QADHLRWLCPCEKT-LOVVWNRFSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@]34C)[C@@H]1CC[C@@H]2O'),
    dict(id='mol:16oh_dhea', es='16α-hidroxi-DHEA', en='16α-Hydroxy-DHEA', corto='16-OH-DHEA',
         family='androgeno', role=['endogena', 'intermediario'], cid=97182, formula='C19H28O3',
         smiles='C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@]34C)[C@@H]1C[C@H](O)C2=O'),

    # ------------------------------------------------------------ gestagenos ---
    dict(id='mol:progesterona', es='Progesterona', en='Progesterone', corto='P4',
         family='gestageno', role=['endogena', 'farmaco'], cid=5994, formula='C21H30O2',
         ik='RJKFOVLPORLFTN-LEKSSAKUSA-N',
         smiles='CC(=O)[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='mol:17oh_progesterona', es='17α-hidroxiprogesterona', en='17α-Hydroxyprogesterone',
         corto='17-OHP', family='gestageno', role=['endogena', 'intermediario'], cid=6238,
         formula='C21H30O3', ik='DBPWSSGDRRHUNT-SJFWLOONSA-N',
         smiles='CC(=O)[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='mol:alopregnanolona', es='Alopregnanolona', en='Allopregnanolone', corto='ALLO',
         family='gestageno', role=['endogena'], cid=92786, formula='C21H34O2',
         ik='AURFZBICLPNKBZ-SYBPFIFISA-N',
         smiles='CC(=O)[C@H]1CC[C@H]2[C@@H]3CC[C@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='mol:17oh_alopregnanolona', es='17α-hidroxialopregnanolona', en='17-OH-Allopregnanolone',
         corto='17-OH-ALLO', family='gestageno', role=['endogena', 'intermediario'], cid=101664,
         formula='C21H34O3',
         smiles='CC(=O)[C@]1(O)CC[C@H]2[C@@H]3CC[C@H]4C[C@H](O)CC[C@]4(C)[C@H]3CC[C@]12C'),

    # ------------------------------------------------------------ androgenos ---
    dict(id='mol:androstenediona', es='Androstenediona', en='Androstenedione', corto='A4',
         family='androgeno', role=['endogena', 'intermediario'], cid=6128, formula='C19H26O2',
         ik='AEMFNILZOJDQLW-QAGGRKNESA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@]34C)[C@@H]1CCC2=O'),
    dict(id='mol:testosterona', es='Testosterona', en='Testosterone', corto='T',
         family='androgeno', role=['endogena', 'farmaco'], cid=6013, formula='C19H28O2',
         ik='MUMGGOZAMZWBJJ-DYKIIFRCSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@]34C)[C@@H]1CC[C@@H]2O'),
    dict(id='mol:dht', es='Dihidrotestosterona', en='Dihydrotestosterone', corto='DHT',
         family='androgeno', role=['endogena'], cid=10635, formula='C19H30O2',
         ik='NVKAWKQGWWIWPM-ABEVXSGRSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC[C@H]4CC(=O)CC[C@]34C)[C@@H]1CC[C@@H]2O'),
    dict(id='mol:androstanodiona', es='5α-androstano-3,17-diona', en='5α-Androstanedione',
         corto='5α-dione', family='androgeno', role=['endogena', 'intermediario'], cid=222865,
         formula='C19H28O2',
         smiles='C[C@]12CC[C@H]3[C@@H](CC[C@H]4CC(=O)CC[C@]34C)[C@@H]1CCC2=O'),
    dict(id='mol:androsterona', es='Androsterona', en='Androsterone', corto='Andro',
         family='androgeno', role=['endogena', 'metabolito'], cid=5879, formula='C19H30O2',
         ik='QGXBDMJGAMFCBF-HLUDHZFRSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC[C@H]4C[C@H](O)CC[C@]34C)[C@@H]1CCC2=O'),
    dict(id='mol:androstanodiol', es='5α-androstano-3α,17β-diol', en='3α-Androstanediol',
         corto='3α-diol', family='androgeno', role=['endogena', 'metabolito'], cid=15818,
         formula='C19H32O2', ik='CBMYJHIOYJEBSB-KHOSGYARSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC[C@H]4C[C@H](O)CC[C@]34C)[C@@H]1CC[C@@H]2O'),
    dict(id='mol:11oh_androstenediona', es='11β-hidroxiandrostenediona', en='11β-OH-Androstenedione',
         corto='11OHA4', family='androgeno', role=['endogena', 'intermediario'], cid=94148,
         formula='C19H26O3',
         smiles='C[C@]12C[C@H](O)[C@H]3[C@@H](CCC4=CC(=O)CC[C@]34C)[C@@H]1CCC2=O'),
    dict(id='mol:11ceto_testosterona', es='11-cetotestosterona', en='11-Ketotestosterone',
         corto='11KT', family='androgeno', role=['endogena'], cid=104728, formula='C19H26O3',
         smiles='C[C@]12CC(=O)[C@H]3[C@@H](CCC4=CC(=O)CC[C@]34C)[C@@H]1CC[C@@H]2O'),

    # ------------------------------------------------------------ estrogenos ---
    dict(id='mol:estrona', es='Estrona', en='Estrone', corto='E1',
         family='estrogeno', role=['endogena'], cid=5870, formula='C18H22O2',
         ik='DNXHEGUUPJUMQT-CBZIJGRNSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCc4cc(O)ccc34)[C@@H]1CCC2=O'),
    dict(id='mol:estrona_sulfato', es='Sulfato de estrona', en='Estrone sulfate', corto='E1S',
         family='estrogeno', role=['endogena'], cid=6432595, formula='C18H22O5S',
         ik='JKKFKPJIXZFSSB-CBZIJGRNSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCc4cc(OS(=O)(=O)O)ccc34)[C@@H]1CCC2=O'),
    dict(id='mol:estradiol', es='Estradiol', en='Estradiol', corto='E2',
         family='estrogeno', role=['endogena', 'farmaco'], cid=5757, formula='C18H24O2',
         ik='VOXZDWNPVJITMN-ZBRFXRBCSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCc4cc(O)ccc34)[C@@H]1CC[C@@H]2O'),
    dict(id='mol:estriol', es='Estriol', en='Estriol', corto='E3',
         family='estrogeno', role=['endogena'], cid=5756, formula='C18H24O3',
         ik='PROQIPRRNZUXQM-ZMSHIADSSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCc4cc(O)ccc34)[C@@H]1C[C@H](O)[C@@H]2O'),
    dict(id='mol:estetrol', es='Estetrol', en='Estetrol', corto='E4',
         family='estrogeno', role=['endogena', 'farmaco'], cid=27125, formula='C18H24O4',
         ik='AJIPIJNNOJSSQC-VKXCEXFMSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCc4cc(O)ccc34)[C@@H]1[C@H](O)[C@H](O)[C@@H]2O'),

    # ------------------------------------------------- corticoides de la via ---
    dict(id='mol:doc', es='11-desoxicorticosterona', en='11-Deoxycorticosterone', corto='DOC',
         family='mineralocorticoide', role=['endogena', 'intermediario'], cid=6166, formula='C21H30O3',
         ik='ZESRJSPZRDMNHY-YFWFAHHUSA-N',
         smiles='OCC(=O)[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='mol:corticosterona', es='Corticosterona', en='Corticosterone', corto='B',
         family='mineralocorticoide', role=['endogena', 'intermediario'], cid=5753, formula='C21H30O4',
         ik='OMFXVFTZEKFJBZ-HJTSIMOOSA-N',
         smiles='OCC(=O)[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3[C@@H](O)C[C@]12C'),
    dict(id='mol:18oh_corticosterona', es='18-hidroxicorticosterona', en='18-Hydroxycorticosterone',
         corto='18-OH-B', family='mineralocorticoide', role=['endogena', 'intermediario'], cid=440351,
         formula='C21H30O5', ik='HFSXHZZDNDGLQN-ZVIOFETBSA-N',
         smiles='OCC(=O)[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3[C@@H](O)C[C@]12CO'),
    dict(id='mol:aldosterona', es='Aldosterona', en='Aldosterone', corto='Aldo',
         family='mineralocorticoide', role=['endogena'], cid=5839, formula='C21H28O5',
         ik='PQSUYGKTWSAVDQ-ZVIOFETBSA-N',
         smiles='OCC(=O)[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3[C@@H](O)C[C@]12C=O'),
    dict(id='mol:11_desoxicortisol', es='11-desoxicortisol', en='11-Deoxycortisol', corto='S',
         family='glucocorticoide', role=['endogena', 'intermediario'], cid=440707, formula='C21H30O4',
         ik='WHBHBVVOGNECLV-KWNDPWABSA-N',
         smiles='OCC(=O)[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='mol:cortisol', es='Cortisol', en='Cortisol', corto='F',
         family='glucocorticoide', role=['endogena', 'farmaco'], cid=5754, formula='C21H30O5',
         ik='JYGXADMDTFJGBT-CZFMHFDVSA-N',
         smiles='OCC(=O)[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3[C@@H](O)C[C@]12C'),
    dict(id='mol:cortisona', es='Cortisona', en='Cortisone', corto='E',
         family='glucocorticoide', role=['endogena', 'metabolito'], cid=222786, formula='C21H28O5',
         ik='MFYSYFVPBJMHGN-YMLCXZJMSA-N',
         smiles='OCC(=O)[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3C(=O)C[C@]12C'),
]

# ------------------------------------------------------------------ farmacos ---
D = [
    dict(id='drug:etinilestradiol', es='Etinilestradiol', en='Ethinylestradiol', corto='EE',
         family='estrogeno', role=['farmaco'], cid=5991, formula='C20H24O2',
         ik='BFPYWIDHMRZLRN-SWBPCFCJSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCc4cc(O)ccc34)[C@@H]1CC[C@]2(O)C#C'),
    dict(id='drug:mestranol', es='Mestranol', en='Mestranol', corto='MEE',
         family='estrogeno', role=['farmaco'], cid=6242, formula='C21H26O2',
         ik='IMSSROKUHAOUJS-CRSSMBPESA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCc4cc(OC)ccc34)[C@@H]1CC[C@]2(O)C#C'),
    dict(id='drug:valerato_estradiol', es='Valerato de estradiol', en='Estradiol valerate',
         corto='EV', family='estrogeno', role=['farmaco'], cid=13791, formula='C23H32O3',
         ik='RSEPBGGWRJCQGY-RBRWEJTLSA-N',
         smiles='CCCCC(=O)O[C@H]1CC[C@H]2[C@@H]3CCc4cc(O)ccc4[C@H]3CC[C@]12C'),
    dict(id='drug:equilina', es='Equilina', en='Equilin', corto='Equilina',
         family='estrogeno', role=['farmaco'], cid=9308, formula='C18H20O2',
         ik='WKRLQDKEXYKHJB-HFTRVMKXSA-N',
         smiles='C[C@]12CC[C@H]3C(=CCc4cc(O)ccc34)[C@@H]1CCC2=O'),
    dict(id='drug:noretisterona', es='Noretisterona', en='Norethisterone', corto='NET',
         family='progestageno_sintetico', role=['farmaco'], cid=6230, formula='C20H26O2',
         ik='VIKNJXKGJWUCNN-JBKQDOAHSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@H]34)[C@@H]1CC[C@]2(O)C#C'),
    dict(id='drug:levonorgestrel', es='Levonorgestrel', en='Levonorgestrel', corto='LNG',
         family='progestageno_sintetico', role=['farmaco'], cid=13109, formula='C21H28O2',
         ik='WWYNJERNGUHSAO-ZUHHCLADSA-N',
         smiles='CC[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@H]34)[C@@H]1CC[C@]2(O)C#C'),
    dict(id='drug:gestodeno', es='Gestodeno', en='Gestodene', corto='GSD',
         family='progestageno_sintetico', role=['farmaco'], cid=3033968, formula='C21H26O2',
         ik='SIGSPDASOTUPFS-ZUHHCLADSA-N',
         smiles='CC[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@H]34)[C@@H]1C=C[C@]2(O)C#C'),
    dict(id='drug:desogestrel', es='Desogestrel', en='Desogestrel', corto='DSG',
         family='progestageno_sintetico', role=['farmaco'], cid=40973, formula='C22H30O',
         ik='COCAEMGBBHMFGZ-CIQOUTPZSA-N',
         smiles='C=C1C[C@H]2[C@@H]3CCC4=CCCC[C@H]4[C@@H]3CC[C@]2(CC)[C@]1(O)C#C'),
    dict(id='drug:etonogestrel', es='Etonogestrel', en='Etonogestrel', corto='ENG',
         family='progestageno_sintetico', role=['farmaco'], cid=6917715, formula='C22H28O2',
         ik='VPEWGHNBGGFMKJ-CIQOUTPZSA-N',
         smiles='C=C1C[C@H]2[C@@H]3CCC4=CC(=O)CC[C@H]4[C@@H]3CC[C@]2(CC)[C@]1(O)C#C'),
    dict(id='drug:norgestimato', es='Norgestimato', en='Norgestimate', corto='NGM',
         family='progestageno_sintetico', role=['farmaco'], cid=6540478, formula='C23H31NO3',
         smiles='CC[C@]12CC[C@H]3[C@@H](CCC4=CC(=NO)CC[C@H]34)[C@@H]1CC[C@]2(OC(C)=O)C#C'),
    dict(id='drug:dienogest', es='Dienogest', en='Dienogest', corto='DNG',
         family='progestageno_sintetico', role=['farmaco'], cid=68861, formula='C20H25NO2',
         ik='AZFLJNIPTRTECV-FYQPLNBISA-N',
         smiles='C[C@]12CCC3=C4CCC(=O)C=C4CC[C@H]3[C@@H]1CC[C@]2(O)CC#N'),
    dict(id='drug:drospirenona', es='Drospirenona', en='Drospirenone', corto='DRSP',
         family='progestageno_sintetico', role=['farmaco'], cid=68873, formula='C24H30O3',
         smiles='C[C@]12CC[C@H]3[C@@H]([C@@H]5C[C@H]5C4=CC(=O)CC[C@]34C)[C@@H]1[C@@H]6C[C@H]6[C@]21CCC(=O)O1'),
    dict(id='drug:mpa', es='Acetato de medroxiprogesterona', en='Medroxyprogesterone acetate',
         corto='AMP', family='progestageno_sintetico', role=['farmaco'], cid=6279, formula='C24H34O4',
         ik='PSGAAPLEWMOORI-PEINSRQWSA-N',
         smiles='CC(=O)O[C@]1(C(C)=O)CC[C@H]2[C@@H]3C[C@H](C)C4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:ciproterona_ac', es='Acetato de ciproterona', en='Cyproterone acetate',
         corto='ACP', family='antiandrogeno', role=['farmaco'], cid=9880, formula='C24H29ClO4',
         ik='UWFYSQMTEOIJJG-PPAPLAQFSA-N',
         smiles='CC(=O)[C@]1(OC(C)=O)CC[C@H]2[C@@H]3C=C(Cl)C4=CC(=O)[C@@H]5C[C@@H]5[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:clormadinona_ac', es='Acetato de clormadinona', en='Chlormadinone acetate',
         corto='ACM', family='progestageno_sintetico', role=['farmaco'], cid=9324, formula='C23H29ClO4',
         ik='QMBJSIBWORFWQT-CZZSXQRJSA-N',
         smiles='CC(=O)[C@]1(OC(C)=O)CC[C@H]2[C@@H]3C=C(Cl)C4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:nomegestrol_ac', es='Acetato de nomegestrol', en='Nomegestrol acetate',
         corto='ANM', family='progestageno_sintetico', role=['farmaco'], cid=443008, formula='C23H30O4',
         smiles='CC(=O)[C@]1(OC(C)=O)CC[C@H]2[C@@H]3C=C(C)C4=CC(=O)CC[C@H]4[C@H]3CC[C@]12C'),
    dict(id='drug:didrogesterona', es='Didrogesterona', en='Dydrogesterone', corto='DYD',
         family='progestageno_sintetico', role=['farmaco'], cid=9051, formula='C21H28O2',
         smiles='CC(=O)[C@H]1CC[C@H]2[C@@H]3C=CC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:tibolona', es='Tibolona', en='Tibolone', corto='TIB',
         family='progestageno_sintetico', role=['farmaco'], cid=444008, formula='C21H28O2',
         ik='BXJNHJHSBKZURR-PZRMFKIPSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](C[C@@H](C)C4=C3CCC(=O)C4)[C@@H]1CC[C@]2(O)C#C'),
    dict(id='drug:mifepristona', es='Mifepristona', en='Mifepristone', corto='RU-486',
         family='sprm', role=['farmaco'], cid=55245, formula='C29H35NO2',
         ik='VKHAHZOOUSRJNA-NVVJBRLPSA-N',
         smiles='CC#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)CCC4=C3[C@@H](c3ccc(N(C)C)cc3)C[C@@]12C'),
    dict(id='drug:ulipristal_ac', es='Acetato de ulipristal', en='Ulipristal acetate', corto='UPA',
         family='sprm', role=['farmaco'], cid=130904, formula='C30H37NO4',
         ik='OOLLAFOLCSJHRE-NSNZNLCHSA-N',
         smiles='CC(=O)[C@]1(OC(C)=O)CC[C@H]2[C@@H]3CCC4=CC(=O)CCC4=C3[C@@H](c3ccc(N(C)C)cc3)C[C@@]12C'),
    dict(id='drug:enantato_testosterona', es='Enantato de testosterona', en='Testosterone enanthate',
         corto='TE', family='androgeno', role=['farmaco'], cid=9416, formula='C26H40O3',
         ik='VOCBWIIFXDYGNZ-IXKNJLPQSA-N',
         smiles='CCCCCCC(=O)O[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:undecanoato_testosterona', es='Undecanoato de testosterona',
         en='Testosterone undecanoate', corto='TU', family='androgeno', role=['farmaco'],
         cid=65157, formula='C30H48O3', ik='UDSFVOAUHKGBEK-CNQKSJKFSA-N',
         smiles='CCCCCCCCCCC(=O)O[C@H]1CC[C@H]2[C@@H]3CCC4=CC(=O)CC[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:nandrolona', es='Nandrolona', en='Nandrolone', corto='ND',
         family='anabolizante', role=['farmaco'], cid=9904, formula='C18H26O2',
         ik='NPAGDVCDWIYMMC-IZPLOLCNSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@H]34)[C@@H]1CC[C@@H]2O'),
    dict(id='drug:oxandrolona', es='Oxandrolona', en='Oxandrolone', corto='OXA',
         family='anabolizante', role=['farmaco'], cid=5878, formula='C19H30O3',
         ik='QSLJIVKCVHQPLV-PEMPUTJUSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC[C@H]4CC(=O)OC[C@]34C)[C@@H]1CC[C@]2(C)O'),
    dict(id='drug:estanozolol', es='Estanozolol', en='Stanozolol', corto='STZ',
         family='anabolizante', role=['farmaco'], cid=25249, formula='C21H32N2O',
         ik='LKAJKIOFIWVMDJ-IYRCEVNGSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC[C@H]4Cc5[nH]ncc5C[C@]34C)[C@@H]1CC[C@]2(C)O'),
    dict(id='drug:mesterolona', es='Mesterolona', en='Mesterolone', corto='MST',
         family='androgeno', role=['farmaco'], cid=15020, formula='C20H32O2',
         ik='GYNLZVFXWMYHPK-DVAVWFTJSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](C[C@@H](C)[C@H]4C[C@H](O)CC[C@]34C)[C@@H]1CCC2=O'),
    dict(id='drug:danazol', es='Danazol', en='Danazol', corto='DNZ',
         family='androgeno', role=['farmaco'], cid=28417, formula='C22H27NO2',
         ik='POZRVZJJTULAOH-LHZXLZLDSA-N',
         smiles='C#C[C@]1(O)CC[C@H]2[C@@H]3CCC4=Cc5oncc5C[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:espironolactona', es='Espironolactona', en='Spironolactone', corto='SPL',
         family='antiandrogeno', role=['farmaco'], cid=5833, formula='C24H32O4S',
         ik='LXMSZDCAJNLERA-GNSLJVCWSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H]([C@@H](SC(C)=O)CC4=CC(=O)CC[C@]34C)[C@@H]1CC[C@]21CCC(=O)O1'),
    dict(id='drug:canrenona', es='Canrenona', en='Canrenone', corto='CAN',
         family='antiandrogeno', role=['farmaco', 'metabolito'], cid=657176, formula='C22H28O3',
         ik='UJVLDDZCTMKXJK-LHZXLZLDSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](C=CC4=CC(=O)CC[C@]34C)[C@@H]1CC[C@]21CCC(=O)O1'),
    dict(id='drug:finasterida', es='Finasterida', en='Finasteride', corto='FIN',
         family='inhibidor_enzimatico', role=['farmaco'], cid=57363, formula='C23H36N2O2',
         ik='DBEPLOCGEIEOCV-WSBQPABSSA-N',
         smiles='CC(C)(C)NC(=O)[C@H]1CC[C@H]2[C@@H]3CC[C@H]4NC(=O)C=C[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:dutasterida', es='Dutasterida', en='Dutasteride', corto='DUT',
         family='inhibidor_enzimatico', role=['farmaco'], cid=6918296, formula='C27H30F6N2O2',
         ik='JWJOTENAMICLJG-QWBYCMEYSA-N',
         smiles='O=C(Nc1cc(C(F)(F)F)ccc1C(F)(F)F)[C@H]1CC[C@H]2[C@@H]3CC[C@H]4NC(=O)C=C[C@]4(C)[C@H]3CC[C@]12C'),
    dict(id='drug:abiraterona', es='Abiraterona', en='Abiraterone', corto='ABI',
         family='inhibidor_enzimatico', role=['farmaco'], cid=132971, formula='C24H31NO',
         ik='GZOSMCIZMLWJML-VJLLXTKPSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC=C4C[C@@H](O)CC[C@]34C)[C@@H]1CC=C2c1cccnc1'),
    dict(id='drug:exemestano', es='Exemestano', en='Exemestane', corto='EXE',
         family='inhibidor_enzimatico', role=['farmaco'], cid=60198, formula='C20H24O2',
         ik='BFYIZQONLCFLEV-DAELLWKTSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H](CC(=C)C4=CC(=O)C=C[C@]34C)[C@@H]1CCC2=O'),
    dict(id='drug:anastrozol', es='Anastrozol', en='Anastrozole', corto='ANA',
         family='inhibidor_enzimatico', role=['farmaco'], cid=2187, formula='C17H19N5',
         ik='YBBLVLTVTVSKRW-UHFFFAOYSA-N',
         smiles='CC(C)(C#N)c1cc(Cn2cncn2)cc(C(C)(C)C#N)c1'),
    dict(id='drug:letrozol', es='Letrozol', en='Letrozole', corto='LET',
         family='inhibidor_enzimatico', role=['farmaco'], cid=3902, formula='C17H11N5',
         ik='HPJKCIUCZWXJDR-UHFFFAOYSA-N',
         smiles='N#Cc1ccc(cc1)C(n1cncn1)c1ccc(cc1)C#N'),
    dict(id='drug:ketoconazol', es='Ketoconazol', en='Ketoconazole', corto='KTZ',
         family='inhibidor_enzimatico', role=['farmaco'], cid=456201, formula='C26H28Cl2N4O4',
         ik='XMAYWYJOQHXEEK-ZEQKJWHPSA-N',
         smiles='CC(=O)N1CCN(CC1)c1ccc(OC[C@@H]2CO[C@](Cn3ccnc3)(O2)c2ccc(Cl)cc2Cl)cc1'),
    dict(id='drug:metirapona', es='Metirapona', en='Metyrapone', corto='MTP',
         family='inhibidor_enzimatico', role=['farmaco'], cid=4174, formula='C14H14N2O',
         ik='FJLBFSROUSIWMA-UHFFFAOYSA-N',
         smiles='CC(C)(c1cccnc1)C(=O)c1cccnc1'),
    dict(id='drug:osilodrostat', es='Osilodrostat', en='Osilodrostat', corto='OSI',
         family='inhibidor_enzimatico', role=['farmaco'], cid=44631912, formula='C13H10FN3',
         smiles='N#Cc1ccc([C@@H]2CCn3cncc23)cc1F'),
    dict(id='drug:tamoxifeno', es='Tamoxifeno', en='Tamoxifen', corto='TAM',
         family='antiestrogeno_serm', role=['farmaco'], cid=2733526, formula='C26H29NO',
         ik='NKANXQFJJICGDU-QPLCGJKRSA-N',
         smiles='CC/C(=C(\\c1ccccc1)c1ccc(OCCN(C)C)cc1)c1ccccc1'),
    dict(id='drug:raloxifeno', es='Raloxifeno', en='Raloxifene', corto='RAL',
         family='antiestrogeno_serm', role=['farmaco'], cid=5035, formula='C28H27NO4S',
         smiles='Oc1ccc2sc(-c3ccc(O)cc3)c(C(=O)c3ccc(OCCN4CCCCC4)cc3)c2c1'),
    dict(id='drug:clomifeno', es='Clomifeno', en='Clomifene', corto='CC',
         family='antiestrogeno_serm', role=['farmaco'], cid=2800, formula='C26H28ClNO',
         ik='GKIRPKYJQBWNGO-UHFFFAOYSA-N',
         smiles='CCN(CC)CCOc1ccc(cc1)C(=C(Cl)c1ccccc1)c1ccccc1'),
    dict(id='drug:ospemifeno', es='Ospemifeno', en='Ospemifene', corto='OSP',
         family='antiestrogeno_serm', role=['farmaco'], cid=3036505, formula='C24H23ClO2',
         ik='LUMKNAVTFCDUIE-UHFFFAOYSA-N',
         smiles='OCCOc1ccc(cc1)C(=C(CCCl)c1ccccc1)c1ccccc1'),
    dict(id='drug:bazedoxifeno', es='Bazedoxifeno', en='Bazedoxifene', corto='BZA',
         family='antiestrogeno_serm', role=['farmaco'], cid=154257, formula='C30H34N2O3',
         smiles='Cc1c(-c2ccc(O)cc2)n(Cc2ccc(OCCN3CCCCCC3)cc2)c2ccc(O)cc12'),
    dict(id='drug:fulvestrant', es='Fulvestrant', en='Fulvestrant', corto='FUL',
         family='antiestrogeno_serm', role=['farmaco'], cid=104741, formula='C32H47F5O3S',
         ik='VWUXBMIQPBEWFH-MSCODYEVSA-N',
         smiles='C[C@]12CC[C@H]3[C@@H]([C@@H](CCCCCCCCCS(=O)CCCC(F)(F)C(F)(F)F)Cc4cc(O)ccc34)[C@@H]1CC[C@@H]2O'),
    dict(id='drug:flutamida', es='Flutamida', en='Flutamide', corto='FLU',
         family='antiandrogeno', role=['farmaco'], cid=3397, formula='C11H11F3N2O3',
         ik='MKXKFYHWDHIYRV-UHFFFAOYSA-N',
         smiles='CC(C)C(=O)Nc1ccc([N+](=O)[O-])c(c1)C(F)(F)F'),
    dict(id='drug:bicalutamida', es='Bicalutamida', en='Bicalutamide', corto='BIC',
         family='antiandrogeno', role=['farmaco'], cid=2375, formula='C18H14F4N2O4S',
         ik='LKJPYSCBVHEWIU-UHFFFAOYSA-N',
         smiles='CC(O)(CS(=O)(=O)c1ccc(F)cc1)C(=O)Nc1ccc(C#N)c(c1)C(F)(F)F'),
    dict(id='drug:enzalutamida', es='Enzalutamida', en='Enzalutamide', corto='ENZ',
         family='antiandrogeno', role=['farmaco'], cid=15951529, formula='C21H16F4N4O2S',
         ik='DKPIYSKPEIWRPE-UHFFFAOYSA-N',
         smiles='CNC(=O)c1ccc(N2C(=O)C(C)(C)N(c3ccc(C#N)c(c3)C(F)(F)F)C2=S)cc1F'),
    dict(id='drug:apalutamida', es='Apalutamida', en='Apalutamide', corto='APA',
         family='antiandrogeno', role=['farmaco'], cid=24872560, formula='C21H15F4N5O2S',
         ik='WDNQVZLULYLAOM-UHFFFAOYSA-N',
         smiles='CNC(=O)c1ccc(N2C(=O)C3(CCC3)N(c3ccc(C#N)c(n3)C(F)(F)F)C2=S)cc1F'),
    dict(id='drug:darolutamida', es='Darolutamida', en='Darolutamide', corto='DAR',
         family='antiandrogeno', role=['farmaco'], cid=67171867, formula='C19H19ClN6O2',
         smiles='C[C@@H](Cn1cc(-c2ccc(C#N)c(Cl)c2)cn1)NC(=O)c1cc(C(C)O)[nH]n1'),
    dict(id='drug:dexametasona', es='Dexametasona', en='Dexamethasone', corto='DXM',
         family='glucocorticoide', role=['farmaco'], cid=5743, formula='C22H29FO5',
         ik='UREBDLICKHMUKA-CXSFZGCWSA-N',
         smiles='C[C@@H]1C[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@@]3(F)[C@@H](O)C[C@]2(C)[C@@]1(O)C(=O)CO'),
    dict(id='drug:prednisolona', es='Prednisolona', en='Prednisolone', corto='PDN',
         family='glucocorticoide', role=['farmaco'], cid=5755, formula='C21H28O5',
         ik='OIGNJSKKLXVSLS-CZFMHFDVSA-N',
         smiles='OCC(=O)[C@]1(O)CC[C@H]2[C@@H]3CCC4=CC(=O)C=C[C@]4(C)[C@H]3[C@@H](O)C[C@]12C'),
]

ALL = M + D
